name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, macos-14, ubuntu-22.04]
        addrsize: ["64"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Homebrew Packages
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        run: |
          choco install nasm
          echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - uses: AlchemyViewer/action-autobuild@v5
        with:
          addrsize: ${{ matrix.addrsize }}
          build-variables-repo: alchemyviewer/build-variables
          build-variables-ref: alchemy
          apt-packages: ninja-build nasm
          brew-packages: ninja nasm
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: alchemyviewer/action-autobuild-release@v4
        with:
          public: true
